#!/usr/bin/env ruby

require "pixel_matcher"

raise ArgumentError, 'Specify two image paths and one output path' unless ARGV.length == 3

path1 = ARGV[0]
path2 = ARGV[1]
output_path = ARGV[2]

diff = PixelMatcher::DiffImage.from_path(path1, path2)
diff.export_diff(output_path)

puts "Generated diff image : #{output_path}"